In [1]:
import numpy as np

In [41]:
A5x2 = np.array ([[1,6],
                [2,8],
                [3,11],
                [3,10],
                [1,7]])

mean_a = (A5x2.mean(axis=0))
a_centerial = A5x2 - mean_a
print('Среднее по признаку: {}'.format(A5x2.mean(axis=0)))
print(a_centerial)

Среднее по признаку: [2.  8.4]
[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [56]:
A = a_centerial[0:5, :1].copy()

print(A)
# выделяем 1-й признак

[[-1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [-1.]]


In [57]:
B = a_centerial[0:5, 1:].copy()

print(B)
# выделяем 2-й признак

[[-2.4]
 [-0.4]
 [ 2.6]
 [ 1.6]
 [-1.4]]


In [58]:
a_centered_sp = A * B
print(a_centered_sp)
# скалярное произведение столбцов массива a_centered

[[ 2.4]
 [-0. ]
 [ 2.6]
 [ 1.6]
 [ 1.4]]


In [70]:
# я не понял что такое количество наблюдений, но понял что это одно целое число, при его замене код будет работать 
N = np.array ([4])
div = a_centered_sp/( N - 1)

print(div)

[[ 0.8       ]
 [-0.        ]
 [ 0.86666667]
 [ 0.53333333]
 [ 0.46666667]]
